### ISSUE TITLE
'kind' value should be ScheduledSession (not 'session')

### ISSUE THREAD

**Issue by thill-odi** [upshot-oa/opendata#3]
Reviewing the output from the validator (https://validator.openactive.io/?url=https%3A%2F%2Fapp.upshot.org.uk%2Fapi%2Fv0%2Fopenactive%2Fv1.0%2F&version=2.0&validationMode=RPDEFeed), it seems the value of the `kind` attribute isn't among the legal values. 

Looking at the data itself, it would appear that the relevant value for this would be `ScheduledSession`, with the parent being a `SessionSeries`, though there are other possibilities (e.g. `Event`, with parent `EventSeries`, which is closer to the current implementation).

**Comment by zerolab** [comment]
'kind' value changed to `Event`

e.g. https://app.upshot.org.uk/api/v0/openactive/v1.0/?afterTimestamp=1580120345509644&afterId=3b03823070e8323b
