### ISSUE TITLE
Events need an Offer

### ISSUE THREAD

**Issue by thill-odi** [upshot-oa/opendata#4]
Reviewing the validator output (https://validator.openactive.io/?url=https%3A%2F%2Fapp.upshot.org.uk%2Fapi%2Fv0%2Fopenactive%2Fv1.0%2F&version=2.0&validationMode=RPDEFeed), it seems that the current feed is missing an `offers` attribute. This is a serious problem, as it prevents end-users from determining how much an event is - and hence middleware consumers from using it at all. 

Even if an event is free of charge, this should be indicated explicitly in the data; most clients will be uncomfortable assuming an event is free if this is not specifically declared.

**Comment by zerolab** [comment]
added a placeholder offer. e.g. https://app.upshot.org.uk/api/v0/openactive/v1.0/?afterTimestamp=1580120345509644&afterId=3b03823070e8323b

There will be further work on integrating with booking systems that will make this more flexible
